name: Run Mobiles Script

on:
  schedule:
    # Run every Saturday at 12 AM IST (6:30 PM UTC on Friday)
    - cron: '30 18 * * 5'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  update-mobiles-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          pip install webdriver-manager
      
      - name: Install Chrome & Chromedriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
          install-chromedriver: true

      - name: Run mobiles.py script
        run: |
          python mobiles.py
      
      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add mobiles.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update mobiles.json data [automated]")
          
          # Set the remote URL with PAT for authentication
          # Using the format username:token for better authentication with organizations
          git remote set-url origin https://${{ secrets.PAT_TOKEN }}@github.com/affdeals/affdeals.github.io.git
          git push